# This workflow build and publishes an npm package to NPM registry

name: Publish Package - NPM registry

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npmjs:
    name: Publish package to npmjs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Setup Web environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn' # or 'npm'

      - name: Install packages
        run: yarn # or 'npm ci'

      - name: Build the plugin
        run: yarn build # or 'npm run build'

      # Need to add npm access token as secret in the repo, named 'NPM_TOKEN' in this case
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
