# This workflow create an Android release APK (unsigned) for flutter application

name: flutter - Android APK

on:
  push:
    paths:
      - '*'
      - '.github/workflows/build-android.yml'
      - 'lib/**'
      - 'assets/**'
      - 'android/**'
      - '!**/*.md'
    branches:
      - main
      - flutter

jobs:
  flutter-build-android:
    # permissions:
    #   contents: write
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java environment in order to build the Android app.
      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      # Setup the flutter environment.
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          cache: true

      # Get flutter dependencies.
      - name: Install Flutter dependencies
        run: flutter pub get

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run tests
      # - run: flutter test

      # Build the Android apk.
      - name: Build Android APK
        run: flutter build apk

      # Upload generated apk to the artifacts.
      - name: Save apk file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-build-android
          path: build/app/outputs/flutter-apk/app-release.apk
