name: Create an iOS Simulator build

on:
  push:
    paths:
      - '*'
      - '.github/workflows/build-ios-simulator.yml'
      - 'android/**'
      - '!**/*.md'
      - '!android/**'
    branches:
      - react-native

jobs:
  build-ios-simulator:
    name: Create an iOS Simulator build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Web environment to install packages.
      - name: Setup Web environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      # Here '--frozen-lockfile' will only use commited 'yarn.lock', and will throw error if some update is needed
      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Install Pod files
        run: npx pod-install ios

      - name: Run simulator build command
        working-directory: ios
        run: |
          xcodebuild -scheme rn_test_github_actions \
          -workspace rn_test_github_actions.xcworkspace \
          -sdk iphonesimulator \
          -configuration Release \
          -derivedDataPath "$(pwd)/build"

      - name: Save apk file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: rn-ios-simulator-build
          path: $(pwd)/build/Build/Products/Release-iphonesimulator/rn_test_github_actions.app