name: Build an Android APK

on:
  push:
    paths:
      - '*'
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'src/**'
      - '!**/*.md'
      - '!ios/**'
    branches:
      - ionic

jobs:
  build-apk:
    permissions:
      contents: write
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Web environment to install packages.
      - name: Setup Web environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Setup Java environment in order to build the Android app.
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install packages
        run: npm install

      - name: Build the ionic project for Android
        run: ionic capacitor build android --prod --no-open

      - name: Build Android debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Save apk file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ionic-actions-test
          path: android/app/build/outputs/apk/debug/app-debug.apk