name: Deploy to GitHub Pages

on:
  push:
    paths:
      - '*'
      - '.github/workflows/gh-pages.yml'
      - 'lib/**'
      - 'web/**'
      - '!**/*.md'
    branches:
      - flutter

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Build Web
        run: flutter build web --base-href /test_github_action_delete/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web