name: Deploy Ionic to GitHub Pages

on:
  push:
    branches:
      - ionic

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install packages
        run: npm install

      - name: Build web
        run: npx ionic build --prod -- --base-href /test_github_action_delete/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www